-- Remove the default PUBLIC EXECUTE privilege from the same internal RPCs.
-- PUBLIC would otherwise make them callable through the Data API despite the anon revoke.
REVOKE EXECUTE ON FUNCTION public.get_platform_secrets() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_platform_secrets(text, text, text, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.asentar_comisiones_faltantes() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.comisiones_no_asentadas() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_paid_accounting_movements(date, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_errores_de_auditoria() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_missing_tax_snapshots() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_orphaned_cfdi_substitutes() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_cobros_sin_comision() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_executive_commission(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_insurance_commission(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_insurance_purchase(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_insurance_settlement(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_membership(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_optional_service(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_payment_plan_installment(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_accounting_entry_for_supplement(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.enforce_accounting_line_integrity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_posted_accounting_entry() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_posted_accounting_entry_deferred() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_posted_accounting_entry_lines() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refresh_commission_on_optional_service() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refresh_commission_on_payment_plan_txn() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refresh_commission_on_supplement() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_agency_commission_from_platform() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.snapshot_booking_tax() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.snapshot_optional_service_tax() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.snapshot_supplement_tax() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.trg_create_accounting_entry_for_penalty_payout() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.trg_insurance_commission_completed() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.trg_insurance_settlement_completed() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_seat_holds() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.clear_documents_submitted_at_on_rejection() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.revocar_sesiones_al_bloquear() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_openpay_topup_updated_at() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_sla_deadline() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.sync_lead_status_on_agency_active() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_agency_documents_updated_at() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_contract_acceptances_updated_at() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.publish_new_terms_version(text, text, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_blocked_ips_count() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_my_sessions(integer, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_remaining_service_fee_exemption(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_wallet_portion_for_booking_component(uuid, numeric) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.request_supplement_with_lock(uuid, uuid, uuid, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.requires_aal2_check() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.generate_agency_slug(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.generate_composite_tour_slug(text, uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_referral_code(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_tour_slug(uuid, text, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION routesred.create_provider(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION routesred.get_user_provider_role(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION routesred.is_provider_member(uuid, text[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION routesred.link_provider_agency(uuid, uuid) FROM PUBLIC, anon;

